
# Common properties spring
server:
  port: 9001

  # Kafka Consumer properties
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      group-id: emergency-group
      key-serializer: com.example.OrderInfoSerializer
      value-serializer: com.example.OrderInfoSerializer

  # Topic name
topic:
  name: quickstart

  # Common Kafka Properties
auto:
  create:
    topics:
      enable: true